package com.mhy.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_goods
 *
 * @mbggenerated do_not_delete_during_merge Wed Jul 20 00:01:33 CST 2016
 */
public class Goods {
    /**
     * Database Column Remarks:
     *   自增主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.id
     *
     * @mbggenerated Wed Jul 20 00:01:33 CST 2016
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   商品名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.name
     *
     * @mbggenerated Wed Jul 20 00:01:33 CST 2016
     */
    private String name;

    /**
     * Database Column Remarks:
     *   商品价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.price
     *
     * @mbggenerated Wed Jul 20 00:01:33 CST 2016
     */
    private Double price;

    /**
     * Database Column Remarks:
     *   上架时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.start_time
     *
     * @mbggenerated Wed Jul 20 00:01:33 CST 2016
     */
    private Date startTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.id
     *
     * @return the value of t_goods.id
     *
     * @mbggenerated Wed Jul 20 00:01:33 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.id
     *
     * @param id the value for t_goods.id
     *
     * @mbggenerated Wed Jul 20 00:01:33 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.name
     *
     * @return the value of t_goods.name
     *
     * @mbggenerated Wed Jul 20 00:01:33 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.name
     *
     * @param name the value for t_goods.name
     *
     * @mbggenerated Wed Jul 20 00:01:33 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.price
     *
     * @return the value of t_goods.price
     *
     * @mbggenerated Wed Jul 20 00:01:33 CST 2016
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.price
     *
     * @param price the value for t_goods.price
     *
     * @mbggenerated Wed Jul 20 00:01:33 CST 2016
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.start_time
     *
     * @return the value of t_goods.start_time
     *
     * @mbggenerated Wed Jul 20 00:01:33 CST 2016
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.start_time
     *
     * @param startTime the value for t_goods.start_time
     *
     * @mbggenerated Wed Jul 20 00:01:33 CST 2016
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }
}