package com.mhy.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_sys_log
 *
 * @mbggenerated do_not_delete_during_merge Wed Jul 20 00:02:06 CST 2016
 */
public class SysLog {
    /**
     * Database Column Remarks:
     *   自增主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_log.id
     *
     * @mbggenerated Wed Jul 20 00:02:06 CST 2016
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   操作类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_log.operate_type
     *
     * @mbggenerated Wed Jul 20 00:02:06 CST 2016
     */
    private String operateType;

    /**
     * Database Column Remarks:
     *   方法
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_log.method
     *
     * @mbggenerated Wed Jul 20 00:02:06 CST 2016
     */
    private String method;

    /**
     * Database Column Remarks:
     *   日志记录时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_log.add_time
     *
     * @mbggenerated Wed Jul 20 00:02:06 CST 2016
     */
    private Date addTime;

    /**
     * Database Column Remarks:
     *   操作内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_log.content
     *
     * @mbggenerated Wed Jul 20 00:02:06 CST 2016
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_log.id
     *
     * @return the value of t_sys_log.id
     *
     * @mbggenerated Wed Jul 20 00:02:06 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_log.id
     *
     * @param id the value for t_sys_log.id
     *
     * @mbggenerated Wed Jul 20 00:02:06 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_log.operate_type
     *
     * @return the value of t_sys_log.operate_type
     *
     * @mbggenerated Wed Jul 20 00:02:06 CST 2016
     */
    public String getOperateType() {
        return operateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_log.operate_type
     *
     * @param operateType the value for t_sys_log.operate_type
     *
     * @mbggenerated Wed Jul 20 00:02:06 CST 2016
     */
    public void setOperateType(String operateType) {
        this.operateType = operateType == null ? null : operateType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_log.method
     *
     * @return the value of t_sys_log.method
     *
     * @mbggenerated Wed Jul 20 00:02:06 CST 2016
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_log.method
     *
     * @param method the value for t_sys_log.method
     *
     * @mbggenerated Wed Jul 20 00:02:06 CST 2016
     */
    public void setMethod(String method) {
        this.method = method == null ? null : method.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_log.add_time
     *
     * @return the value of t_sys_log.add_time
     *
     * @mbggenerated Wed Jul 20 00:02:06 CST 2016
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_log.add_time
     *
     * @param addTime the value for t_sys_log.add_time
     *
     * @mbggenerated Wed Jul 20 00:02:06 CST 2016
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_log.content
     *
     * @return the value of t_sys_log.content
     *
     * @mbggenerated Wed Jul 20 00:02:06 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_log.content
     *
     * @param content the value for t_sys_log.content
     *
     * @mbggenerated Wed Jul 20 00:02:06 CST 2016
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}