package com.mhy.dao;

import com.mhy.model.Goods;

public interface GoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbggenerated Wed Jul 20 00:01:33 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbggenerated Wed Jul 20 00:01:33 CST 2016
     */
    int insert(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbggenerated Wed Jul 20 00:01:33 CST 2016
     */
    int insertSelective(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbggenerated Wed Jul 20 00:01:33 CST 2016
     */
    Goods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbggenerated Wed Jul 20 00:01:33 CST 2016
     */
    int updateByPrimaryKeySelective(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbggenerated Wed Jul 20 00:01:33 CST 2016
     */
    int updateByPrimaryKey(Goods record);
}