package com.mhy.dao;

import com.mhy.model.SysLog;

public interface SysLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_log
     *
     * @mbggenerated Wed Jul 20 00:02:06 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_log
     *
     * @mbggenerated Wed Jul 20 00:02:06 CST 2016
     */
    int insert(SysLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_log
     *
     * @mbggenerated Wed Jul 20 00:02:06 CST 2016
     */
    int insertSelective(SysLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_log
     *
     * @mbggenerated Wed Jul 20 00:02:06 CST 2016
     */
    SysLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_log
     *
     * @mbggenerated Wed Jul 20 00:02:06 CST 2016
     */
    int updateByPrimaryKeySelective(SysLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_log
     *
     * @mbggenerated Wed Jul 20 00:02:06 CST 2016
     */
    int updateByPrimaryKey(SysLog record);
}